apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-hasher
  labels:
    app: user-hasher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-hasher
  template:
    metadata:
      labels:
        app: user-hasher
    spec:
      containers:
      - name: user-hasher
        image: ghoshpra/userhasher:1.0.8
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
        env:
          - name: USER_SALT
            valueFrom:
              secretKeyRef:
                name: user-salt
                key: USER_SALT